### ISSUE TITLE
REST API proposal

### ISSUE THREAD

**Issue by davidfowl** [BoopChat/boop#15]
**Auth**

- POST /login/auth/{provider} - Associate user with local account (if needed) and return JWT token, that encapsulates the user id and other user information, that must be used for subsequent API calls.
```JSON
{
  "userid": "34678",
  "email": "foo@bar.com"
}
````

The following API calls are all authenticated and require the JWT token from the login endpoint to call. This means that each of these APIs scoped to a user.

**Users**
- GET /user - Get a user's information

**Conversations**
- POST /conversations/ - Create a conversation (passing a list of contact ids)
```JSON
{
  "contacts": [ 12, 23, 45 ]
}
```

- GET /conversations - Get all conversations for a user
- DELETE /conversations/{conversationId} - Delete a conversation (maybe a soft delete)

**Contacts**
- GET /contacts/ - Get a user's contact list
- POST /contacts/{contactEmail}  - Add a contact for a this user by email
- DELETE /contacts/{contactId} - Delete a contact

**Messages**
- POST /messages/{conversationId} - Add a new message to a conversation
- GET /messages/{conversationId} - Get chat history for a conversation (this needs to be paged)

**Comment by krazeelazy** [comment]
Started working on this in PR #23  and PR #26.

**Comment by davidfowl** [comment]
This all done!? Nice!

**Comment by krazeelazy** [comment]
> This all done!? Nice!

Yup. We just have to build on the login stuff but the basics are there and functional.
