### ISSUE TITLE
Implement queries for REST API

### ISSUE THREAD

**Issue by davidfowl** [BoopChat/boop#35]
The [REST API](https://github.com/BoopChat/boop/issues/15) needs to implement specific queries for the MVP:

Login
- [x] Get user id given an email and provider name

Conversations
- [x] Create conversation given a list of participants
- [x] Get all conversations for a user
- [x] Delete a conversation for a user

Contacts
- [x] Get all contacts for a user
- [x] Add contact by email
- [x] Delete a contact

Messages
- [x] Add a new message to a conversation
- [x] Get recent messages for a conversation ordered by last created descending

**Comment by krazeelazy** [comment]
Does deleting a conversation for a user mean deleting the user as a participant and removing their messages or just doing a soft delete so the user doesn't see the chat anymore?

**Comment by davidfowl** [comment]
I don't know. I think that's up for us to decide. What do you think it should do?

**Comment by krazeelazy** [comment]
I think it would be better if we called it "leave chat" and do the soft delete. It would be better for people that are still in the chat after the user leaves. It would be confusing if there are giant gaps in the conversation if someone is trying to reread the chat history.

We would also have to decide what happens if the only admin tries to leave the chat. Is a new 1 chosen at random? Is the entire chat deleted? Do they have to choose a new admin before they can leave?

**Comment by JChris246** [comment]
> I think it would be better if we called it "leave chat" and do the soft delete. It would be better for people that are still in the chat after the user leaves. It would be confusing if there are giant gaps in the conversation if someone is trying to reread the chat history.
> 
> We would also have to decide what happens if the only admin tries to leave the chat. Is a new 1 chosen at random? Is the entire chat deleted? Do they have to choose a new admin before they can leave?

I believe either making the current admin choose a successor just before leaving or choosing the new admin from the remaining participants based on who was in the chat longest (random for any that have the same length) would be a good idea.

**Comment by JChris246** [comment]
How do you leave a 1 on 1 chat tho?

**Comment by krazeelazy** [comment]
> How do you leave a 1 on 1 chat tho?

In the delete function we could do a check for number of participants and if the last participant is trying to leave then actually delete the entire conversation?

**Comment by krazeelazy** [comment]
> > I think it would be better if we called it "leave chat" and do the soft delete. It would be better for people that are still in the chat after the user leaves. It would be confusing if there are giant gaps in the conversation if someone is trying to reread the chat history.
> > 
> > We would also have to decide what happens if the only admin tries to leave the chat. Is a new 1 chosen at random? Is the entire chat deleted? Do they have to choose a new admin before they can leave?
> 
> I believe either making the current admin choose a successor just before leaving or choosing the new admin from the remaining participants based on who was in the chat longest (random for any that have the same length) would be a good idea. 

I kind of like making the admin choose a successor. It was their chat, they should choose who to leave in charge I guess.

**Comment by JChris246** [comment]
> In the delete function we could do a check for number of participants and if the last participant is trying to leave then actually delete the entire conversation?
> 
> Also during creation if the number of participants is 2 should both be set as admins?

This seems fine

**Comment by kac246** [comment]
> > I think it would be better if we called it "leave chat" and do the soft delete. It would be better for people that are still in the chat after the user leaves. It would be confusing if there are giant gaps in the conversation if someone is trying to reread the chat history.
> > We would also have to decide what happens if the only admin tries to leave the chat. Is a new 1 chosen at random? Is the entire chat deleted? Do they have to choose a new admin before they can leave?
> 
> I believe either making the current admin choose a successor just before leaving or choosing the new admin from the remaining participants based on who was in the chat longest (random for any that have the same length) would be a good idea.

I like the idea of the admin choosing a successor before they leave and they are only able to leave the chat once they select someone.

**Comment by kac246** [comment]
> > How do you leave a 1 on 1 chat tho?
> 
> In the delete function we could do a check for number of participants and if the last participant is trying to leave then actually delete the entire conversation?
> 
> Also during creation if the number of participants is 2 should both be set as admins?

Sounds good.
