### ISSUE TITLE
Centralize shared state

### ISSUE THREAD

**Issue by JChris246** [BoopChat/boop#66]
<b>Problem</b>:
As the application grows, certain pieces of state within the app now need to be shared across larger subsections of the app. As a result, the state is passed around via props and in some instances with callback functions. This leaves some of the functionality in an inconsistent state. 

<b>Proposed solution</b>
The state such as `conversations`, `contacts`, `socket` etc, for example, should be removed from their associated components (`Conversations` and `Contacts`) and be placed within a centralized store (possibly a redux store), so they can be updated; for example in the `Chats` component when a user adds a new participant to a conversation. The changes would then be reflected in real-time in the necessary locations.

**Comment by krazeelazy** [comment]
This sounds reasonable. 
Something like redux thunk, a central store, root reducer and a redux action-reducer pattern (server requests in actions and interpreting responses and updating the root reducer and store in the reducers) could be useful.
